import styles from '../../styles/Home.module.css'
import Head from 'next/head'

function HeaderComponent() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.header}>
                <h>header</h>
            </div>
        </>


    )
}
export default HeaderComponent;